wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
    start_time: 1637339132
    t:
      1:
      - 1
      - 9
      2:
      - 1
      - 9
      3:
      - 13
      4: 3.6.8
      5: 0.12.6
      8:
      - 5
